function [fitresult1, gof1, fitresult2, gof2, fitresult3, gof3] = logistic_fit_combined(time, S1, S1_2, S1_3)
%CREATEFIT(TIME,S1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : time
%      Y Output: S1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Aug-2020 12:12:53


%% Fit: 'untitled fit 1'.
[xData1, yData1] = prepareCurveData( time, S1 );
[xData2, yData2] = prepareCurveData( time, S1_2 );
[xData3, yData3] = prepareCurveData( time, S1_3 );

% Set up fittype and options.
ft = fittype( 'K./(1+((K-0.1)/0.1)*exp(-r*(t)))', 'independent', 't', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.950222048838355 0.0344460805029088];

% Fit model to data.
[fitresult1, gof1] = fit( xData1, yData1, ft, opts );
[fitresult2, gof2] = fit( xData2, yData2, ft, opts );
[fitresult3, gof3] = fit( xData3, yData3, ft, opts );

% Plot fit with data.
figure( 'Name', 'Logistic Fit' );
h = plot( fitresult1, xData1, yData1);
hold on
h2 = plot( fitresult2, xData2, yData2);
h3 = plot( fitresult3, xData3, yData3);

set(h, 'Color',[0 0.4470 0.7410]);
set(h2, 'Color',[0.6350 0.0780 0.1840]);
set(h3, 'Color',[0.9290 0.6940 0.1250]);

legend( h, 'S1_1', 'Logistic Fit 1', h2, 'S1_2', 'Logistic Fit 2',h3, 'S1_3', 'Logistic Fit 3');
% Label axes
xlabel( 'Time (hr-1)', 'Interpreter', 'none' );
ylabel( 'OD', 'Interpreter', 'none' );
grid on



