function [fitresult, gof] = logistic_fit(time_green, droplet_55_1)
%CREATEFIT1(TIME_GREEN,DROPLET_55_1)
%  Create a fit.
%
%  Data for 'monoculture' fit:
%      X Input : time_green
%      Y Output: droplet_55_1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Jul-2020 12:55:22


%% Fit: 'monoculture'.
[xData, yData] = prepareCurveData( time_green, droplet_55_1 );

% Set up fittype and options.
ft = fittype( 'K./(1+((K./1)-1)*exp(-r*(t)))', 'independent', 't', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0];
opts.StartPoint = [100 0.01];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'monoculture' );
h = plot( fitresult, xData, yData );
legend( h, 'droplet_55_1 vs. time_green', 'monoculture', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'time_green', 'Interpreter', 'none' );
ylabel( 'droplet_55_1', 'Interpreter', 'none' );
grid on


